### PR TITLE
One Month Submission for Chris

### PR DESCRIPTION
**Pull request by clf0022git**
# Pull Request Name/Title
Let us know what added/removed/changed here. Make sure that you have completed the PR Checklist below before you open the PR publicly.

# Category
- [ X] One-Month Project Submission
- [ ] Bug Fix

# PR Checklist
Complete this checklist before opening your 
- [ ] If the PR is a bug fix, the issue is linked in the PR Content
- [ Public (might change later)] If this PR is a One-Month submission, include if you want your site to be listed publicly on our website.
- [ ] If this PR is a work in progress, it's name starts with `WIP:`. Example: `WIP: Nathan Solomon One-Month Submission`

### CODE REVIEW

**Review by hestes835 — DISMISSED** [review]
Bingus. Approved.

**Review by salsajeries — DISMISSED** [review]
I approve this message

**Review by jestes15 — CHANGES_REQUESTED** [review]
Please remove Visual Studio solution files. They have your user name from the Windows PC this project was developed on.

**Review by jestes15 — APPROVED** [review]

**Review by salsajeries — APPROVED** [review]
Approved by me

**Review by hestes835 — APPROVED** [review]

**Pull request merged**
