### PR TITLE
WIP: Website Redesign

### PR DESCRIPTION
**Pull request by jestes15**
# Website Redesign
Changed the UI of the website and converted all navbars to the new look. Deprecated the Calendar page. 
WIP: Change pictures to updated pictures.

# Category
- [x] Bug Fix

# PR Checklist
Complete this checklist before opening your 
- [x] If the PR is a bug fix, the issue is linked in the PR Content
- [x] PR is a work in progress

### CODE REVIEW

**Review by Jedimaster4559 — DISMISSED** [review]
Looks pretty good. A couple of thoughts. First, please don't upload your `.idea` directory. if you need to, add that folder to the main `.gitignore`.

Also not sure how I feel about keeping the old photos that we no longer need. It's probably fine for now, but I'm not sure what our storage restrictions are on the server.

I didn't load this up locally, but I'm assuming everything works and generally looks good. Here's a quick checklist though:
- [x] Does it look right in edge
- [x] Does it look right in Chrome
- [x] Does it look right in Firefox

I guess this also brings up a point that we should probably add some type of linter to our build process.

**Comment by sel3450** [comment]
I doubt we will use the calendar page, but maybe we can update it to give directions to the Charger Connect.

**Comment by sel3450** [comment]
Looks good.

**Review by sel3450 — APPROVED** [review]

**Comment by Jedimaster4559** [comment]
> I doubt we will use the calendar page, but maybe we can update it to give directions to the Charger Connect.

Perhaps it might be possible to link embed some type of charger connect calendar? (not sure how charger connect works)

**Review by Jedimaster4559 — APPROVED** [review]
looks good. As I mentioned, there are some code style issues here, but I don't think we can resolve any of those without adding a code linting check to the ci. (perhaps a good idea for someone's one month project)?

**Comment by Jedimaster4559** [comment]
Also, make sure to Squash and Merge this so as to not screw up the git history too much.

**Comment by jestes15** [comment]
> Also, make sure to Squash and Merge this so as to not screw up the git history too much.

Will do Nathan. Thank you!
I plan on working on the code style issue in one of my next PRs. Will make an issue for it.

**Review by hestes835 — APPROVED** [review]
looks good.  I agree that I don't think anyone's going to keep up with the calendar.

**Comment by jestes15** [comment]
And now time to hope the website updates

**Comment by Jedimaster4559** [comment]
> And now time to hope the website updates

Should already be updated. The ci pipeline takes less than 30 seconds when its not rebuilding the whole site from scratch.

**Comment by jestes15** [comment]
> > And now time to hope the website updates
> 
> Should already be updated. The ci pipeline takes less than 30 seconds when its not rebuilding the whole site from scratch.

It did, and it broke somehow. im trying to see why, but as far as i can tell, some of the stuff didnt load onto the server kinda odd

**Pull request merged**
