### PR TITLE
Adding my website

### PR DESCRIPTION
**Pull request by amjohns1**
# Pull Request Name / Title
Let us know what added/removed/changed here. Make sure that you have completed the PR Checklist below before you open the PR publicly.

# Category
- [ X] One-Month Project Submission
- [ ] Bug Fix

# PR Checklist
Complete this checklist before opening your 
- [ ] If the PR is a bug fix, the issue is linked in the PR Content
- [ X] If this PR is a One-Month submission, include if you want your site to be listed publicly on our website.
- [ ] If this PR is a work in progress, it's name starts with `WIP:`. Example: `WIP: Nathan Solomon One-Month Submission`

### CODE REVIEW

**Review by hestes835 — APPROVED** [review]
Looks good, the top navigation bar does not seem to work on my end though.
Feel free to update if the other reviewers catch it.

**Review by Actual-Heathen — APPROVED** [review]
looks fine.

**Review by salsajeries — APPROVED** [review]
I approve this message

**Review by jestes15 — COMMENTED** [review]
I would probably remove the phone number and personal email from the resume since this will be on the website until you take it down.

**Pull request merged**
