### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by umang171**
# Pull Request Name / Title
Let us know what added/removed/changed here. Make sure that you have completed the PR Checklist below before you open the PR publicly.

# Category
- [ ] One-Month Project Submission
- [ ] Bug Fix

# PR Checklist
Complete this checklist before opening your 
- [ ] If the PR is a bug fix, the issue is linked in the PR Content
- [ ] If this PR is a One-Month submission, include if you want your site to be listed publicly on our website.
- [ ] If this PR is a work in progress, it's name starts with `WIP:`. Example: `WIP: Nathan Solomon One-Month Submission`

### CODE REVIEW

**Comment by Jedimaster4559** [comment]
This seems to be almost entirely white space updates. I'm probably going to reject this PR unless the original poster has some update for us here.

**Review by Duke02 — CHANGES_REQUESTED** [review]
Agree with Nathan. This is just new lines that have been inserted.

**Review by Jedimaster4559 — CHANGES_REQUESTED** [review]
Just whitespace. Not a meaningful contribution.

**Review by sel3450 — CHANGES_REQUESTED** [review]
Just white space updates.

**Pull request closed without merging**
