### PR TITLE
Update to README.md

### PR DESCRIPTION
**Pull request by jestes15**
# Update to README.md and other bug fixes

## Improvements/Bug Fixes
- Updated the README.md
- Fixed a big with the JS code where it lost the membersites page after being resized from mobile

## Category
- [x] Bug Fix

### CODE REVIEW

**Review by hestes835 — APPROVED** [review]
Looks good

**Comment by salsajeries** [comment]
looks good pt 2

**Review by salsajeries — COMMENTED** [review]
actually now it's good

**Comment by jestes15** [comment]
> actually now it's good

You only commented on it, not approved it.

**Review by Actual-Heathen — APPROVED** [review]
ReadIt

**Pull request merged**
