### PR TITLE
Jacob Warren / One Month Submission

### PR DESCRIPTION
**Pull request by jdww5567**
# Pull Request Name / Title
Let us know what added/removed/changed here. Make sure that you have completed the PR Checklist below before you open the PR publicly.

# Category
- [X ] One-Month Project Submission
- [ ] Bug Fix

# PR Checklist
Complete this checklist before opening your pull request
- [ ] If the PR is a bug fix, the issue is linked in the PR Content
- [ ] If this PR is a One-Month submission, include if you want your site to be listed publicly on our website.
- [ ] If this PR is a work in progress, it's name starts with `WIP:`. Example: `WIP: Nathan Solomon One-Month Submission`

### CODE REVIEW

**Comment by salsajeries** [comment]
Needs a link back to the UAH ACM Website:

<a href="https://uah.acm.org/">Back to ACM</a>

**Review by salsajeries — CHANGES_REQUESTED** [review]
Needs a link back to the UAH ACM Website:

`<a href="https://uah.acm.org/">Back to ACM</a>`

**Comment by jdww5567** [comment]
image
It does currently have a link back to the UAH ACM Website. Does it have to contain the exact same text: "Back to ACM"?

**Review by salsajeries — APPROVED** [review]
You're right, it's there!

**Pull request merged**
