### PR TITLE
Changed runs-on

### PR DESCRIPTION
**Pull request by jestes15**
# Changed runs-on in the GitHub workflow
`runs-on: self-hosted` changed to `runs-on: ubuntu-latest`

# Category
- [x] Bug Fix

### CODE REVIEW

**Review by hestes835 — APPROVED** [review]
thank you josh, very cool

**Review by salsajeries — APPROVED** [review]
I approve this message 👍

**Review by BattleHardened64 — APPROVED** [review]
So it just swaps from self-hosted, to the latest version of Ubuntu?  Will that affect compatibility with Nathan's servers?

**Comment by jestes15** [comment]
> So it just swaps from self-hosted, to the latest version of Ubuntu?  Will that affect compatibility with Nathan's servers?

It will be running using GitHub's runners and not Nathan's.

**Comment by BattleHardened64** [comment]
Ahhh okay.  In that case yep yep all good approved on my end

**Pull request merged**
