### PR TITLE
Justin Fleming One-Month Project Submission(Include on site)

### PR DESCRIPTION
**Pull request by RedSweaterBill**
# Pull Request Name / Title
Let us know what added/removed/changed here. Make sure that you have completed the PR Checklist below before you open the PR publicly.

# Category
- [X] One-Month Project Submission
- [ ] Bug Fix

# PR Checklist
Complete this checklist before opening your pull request
- [ ] If the PR is a bug fix, the issue is linked in the PR Content
- [X] If this PR is a One-Month submission, include if you want your site to be listed publicly on our website.
- [ ] If this PR is a work in progress, it's name starts with `WIP:`. Example: `WIP: Nathan Solomon One-Month Submission`

### CODE REVIEW

**Comment by salsajeries** [comment]
lgtm! i lost the game tho so that's rude :(

**Review by salsajeries — APPROVED** [review]
lgtm! i lost the game tho so that's rude :(

**Review by salsajeries — CHANGES_REQUESTED** [review]
Forgot to request changes - Needs a link back to the UAH ACM Website:

<a href="https://uah.acm.org/">Back to ACM</a>

**Review by earocorn — COMMENTED** [review]
Looks good! You'll just need a link back to the UAH ACM website which is https://uah.acm.org

**Review by shorewind — APPROVED** [review]
I like it!

**Review by salsajeries — APPROVED** [review]
lgtm!

**Pull request merged**
