### PR TITLE
WIP: Ian Bohanan One Month Submission

### PR DESCRIPTION
**Pull request by IanBohanan**
# Pull Request Name / Title
I added a wave header files that has floating buoys. Each bouy can be clicked to go to an about page or a home page. This website can be listed publicly.

# Category
- [X ] One-Month Project Submission
- [ ] Bug Fix

# PR Checklist
Complete this checklist before opening your pull request
- [ ] If the PR is a bug fix, the issue is linked in the PR Content
- [ X] If this PR is a One-Month submission, include if you want your site to be listed publicly on our website.
- [ X] If this PR is a work in progress, it's name starts with `WIP:`. Example: `WIP: Nathan Solomon One-Month Submission`

### CODE REVIEW

**Comment by earocorn** [comment]
Lookin good! All it needs is a link somewhere to go back to the UAH ACM website which is https://uah.acm.org

**Comment by salsajeries** [comment]
Needs a link back to the UAH ACM Website:

`<a href="https://uah.acm.org/">Back to ACM</a>`

**Review by salsajeries — CHANGES_REQUESTED** [review]
Needs a link back to the UAH ACM Website:

`<a href="https://uah.acm.org/">Back to ACM</a>`

**Review by salsajeries — APPROVED** [review]
Lgtm!

**Pull request merged**
